View and view groups
ekatrys/AndroidFundaments pull request #1
Opened 2020-11-22 19:07 UTC by ekatrys

2020-11-22 21:10 UTC, PaulXIII requested changes

2020-11-22 21:10 UTC, PaulXIII commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:theme="@style/MyRatingBar"
Для `View` лучше использовать параметр `style`

2020-11-22 21:10 UTC, PaulXIII commented on app/src/main/res/values-v28/text_style.xml
> +        <item name="fontFamily">@font/roboto</item>
Шрифт `roboto` используется в каждом стиле.
Лучше всего создать базовый стиль с общими параметрами

2020-11-22 21:10 UTC, PaulXIII commented on app/src/main/res/values/text_style.xml
> +        <item name="fontFamily">@font/roboto</item>
Так же стоит поравить стиль

2020-11-22 21:10 UTC, PaulXIII commented on app/src/main/res/values/themes.xml
> +    <style name="MyRatingBar" parent="Theme.AppCompat">
Для `View` всегда лучше применять специальный стиль. В случае дизайна подойдет стиль `Widget.AppCompat.RatingBar.Small`

2020-11-23 10:39 UTC, ekatrys commented on app/src/main/res/layout/activity_movie_details.xml
> +
> Не хватает кнопки назад как в дизайне
> https://www.figma.com/file/p3e0HZexHmxwQaN9NcwAD9/Android-Academy?node-id=82%3A2

добавила

2020-11-23 10:40 UTC, ekatrys commented on app/src/main/res/values/text_style.xml
> +        <item name="fontFamily">@font/roboto</item>
добавила общий стиль

2020-11-24 17:17 UTC, PaulXIII requested changes

2020-11-24 17:17 UTC, PaulXIII commented on app/src/main/res/layout/activity_movie_details.xml
> +                app:theme="@style/BackButton" />
Для стилизации кнопки лучше использовать параметр `style`

2020-11-25 15:18 UTC, PaulXIII approved these changes

2020-11-29 22:34 UTC, merged